import { CommonModule } from '@angular/common';
import { Component, computed, input, output, signal } from '@angular/core';

/**
 * Validation error emitted by SkFileUploadComponent when a selected file
 * does not comply with the configured upload constraints.
 */
export interface SkFileUploadError {
  /** File that caused the error, when the error is related to a specific file. */
  file?: File;

  /** Machine-readable error code that can be mapped to translated messages. */
  code: 'invalid-type' | 'max-size' | 'max-files';

  /** User-readable error message generated by the component. */
  message: string;
}

/**
 * Reusable file upload component for Skolans.
 *
 * Supports click-to-select and drag-and-drop uploads, optional multiple files,
 * file type validation, file size validation, image preview, and file removal.
 *
 * Current usage includes tenant logo uploads, but the API is intentionally
 * generic so it can be reused for documents, attachments, or bulk uploads.
 */
@Component({
  selector: 'app-sk-file-upload',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './sk-file-upload.component.html',
  styleUrl: './sk-file-upload.component.scss',
})
export class SkFileUploadComponent {
  /** Optional label displayed above the upload area. */
  readonly label = input<string>('');

  /** Optional helper text displayed below the label. */
  readonly helper = input<string>('');

  /**
   * Accepted file types using the same syntax as the native file input.
   * Examples: `image/*`, `.pdf`, `image/png,image/jpeg`.
   */
  readonly accept = input<string>('image/*');

  /** Enables multiple file selection and drop handling. */
  readonly multiple = input<boolean>(false);

  /** Maximum allowed size per file, expressed in megabytes. */
  readonly maxSizeMb = input<number>(2);

  /** Maximum number of files allowed when `multiple` is enabled. */
  readonly maxFiles = input<number>(1);

  /** Disables the input, drag-and-drop behavior, and remove actions. */
  readonly disabled = input<boolean>(false);

  /** Text displayed inside the drop area when no file is selected. */
  readonly placeholder = input<string>('Arrastra un archivo aquí o haz clic para seleccionarlo.');

  /** Emits the current list of valid selected files after every valid change. */
  readonly filesChange = output<File[]>();

  /** Emits validation errors without mutating the current valid selection. */
  readonly uploadError = output<SkFileUploadError>();

  /** Internal list of currently selected valid files. */
  protected readonly files = signal<File[]>([]);

  /** Tracks drag state to render visual feedback in the dropzone. */
  protected readonly isDragging = signal<boolean>(false);

  /** Preview URL for the first selected image file. */
  protected readonly previewUrl = computed(() => {
    const file = this.files()[0];

    if (!file || !file.type.startsWith('image/')) {
      return null;
    }

    return URL.createObjectURL(file);
  });

  /** Comma-separated list of selected file names for display. */
  protected readonly fileNames = computed(() => {
    return this.files().map((file) => file.name).join(', ');
  });

  /**
   * Handles files selected through the hidden native input.
   */
  protected onInputChange(event: Event): void {
    const inputElement = event.target as HTMLInputElement;
    const files = Array.from(inputElement.files ?? []);

    this.handleFiles(files);
    inputElement.value = '';
  }

  /**
   * Enables drop behavior and activates dragging visual state.
   */
  protected onDragOver(event: DragEvent): void {
    event.preventDefault();

    if (this.disabled()) {
      return;
    }

    this.isDragging.set(true);
  }

  /**
   * Clears dragging visual state when the pointer leaves the dropzone.
   */
  protected onDragLeave(event: DragEvent): void {
    event.preventDefault();
    this.isDragging.set(false);
  }

  /**
   * Handles files dropped into the dropzone.
   */
  protected onDrop(event: DragEvent): void {
    event.preventDefault();
    this.isDragging.set(false);

    if (this.disabled()) {
      return;
    }

    const files = Array.from(event.dataTransfer?.files ?? []);
    this.handleFiles(files);
  }

  /**
   * Removes a selected file and emits the updated file list.
   */
  protected removeFile(fileToRemove: File): void {
    const nextFiles = this.files().filter((file) => file !== fileToRemove);

    this.files.set(nextFiles);
    this.filesChange.emit(nextFiles);
  }

  /**
   * Clears the current selection and emits an empty list.
   */
  protected clearFiles(): void {
    this.files.set([]);
    this.filesChange.emit([]);
  }

  /**
   * Validates selected files and updates the component state only with files
   * that comply with the configured constraints.
   */
  private handleFiles(selectedFiles: File[]): void {
    if (this.disabled() || selectedFiles.length === 0) {
      return;
    }

    const limit = this.multiple() ? this.maxFiles() : 1;

    if (selectedFiles.length > limit) {
      this.uploadError.emit({
        code: 'max-files',
        message: `Solo puedes seleccionar ${limit} archivo(s).`,
      });
      return;
    }

    const validFiles: File[] = [];

    for (const file of selectedFiles) {
      if (!this.isAcceptedType(file)) {
        this.uploadError.emit({
          file,
          code: 'invalid-type',
          message: `El archivo ${file.name} no tiene un formato permitido.`,
        });
        continue;
      }

      if (!this.isAcceptedSize(file)) {
        this.uploadError.emit({
          file,
          code: 'max-size',
          message: `El archivo ${file.name} supera el tamaño máximo de ${this.maxSizeMb()} MB.`,
        });
        continue;
      }

      validFiles.push(file);
    }

    if (validFiles.length === 0) {
      return;
    }

    const nextFiles = this.multiple() ? validFiles : [validFiles[0]];

    this.files.set(nextFiles);
    this.filesChange.emit(nextFiles);
  }

  /**
   * Checks whether a file is within the configured maximum size.
   */
  private isAcceptedSize(file: File): boolean {
    const maxBytes = this.maxSizeMb() * 1024 * 1024;

    return file.size <= maxBytes;
  }

  /**
   * Checks whether a file matches the configured accept pattern.
   */
  private isAcceptedType(file: File): boolean {
    const accept = this.accept().trim();

    if (!accept) {
      return true;
    }

    const allowedTypes = accept.split(',').map((type) => type.trim().toLowerCase());
    const fileName = file.name.toLowerCase();
    const fileType = file.type.toLowerCase();

    return allowedTypes.some((type) => {
      if (type === '*/*') {
        return true;
      }

      if (type.endsWith('/*')) {
        return fileType.startsWith(type.replace('/*', '/'));
      }

      if (type.startsWith('.')) {
        return fileName.endsWith(type);
      }

      return fileType === type;
    });
  }
}
